   name: Build and Deploy to Cloud Run

   on:
     push:
       branches:
         - main

   jobs:
     build-and-deploy:
       runs-on: ubuntu-latest

       steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up Google Cloud SDK
           uses: google-github-actions/setup-gcloud@v1
           with:
             version: 'latest'
             project_id: ${{ secrets.GCP_PROJECT_ID }}
             service_account_key: ${{ secrets.GCP_SA_KEY }}

         - name: Build and push Docker image to Google Container Registry
           run: |
             gcloud auth configure-docker
             docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/simple-python-docker:$GITHUB_SHA .
             docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/simple-python-docker:$GITHUB_SHA

         - name: Deploy to Cloud Run
           run: |
             gcloud run deploy simple-python-docker \
               --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/simple-python-docker:$GITHUB_SHA \
               --platform managed \
               --region us-central1 \
               --allow-unauthenticated
